#ifndef MULTICAST_H
#define MULTICAST_H

#define MULTICAST_ADDR "234.5.6.7"
#define MULTICAST_PORT 8910
#define CONTROL_PORT 8911

#define PACKET_SIZE 512
#define MAX_BACKLOG 5
#define MAX_ADDR_SIZE 16

typedef enum command
{
	FILE_LIST, USER_LIST, MESSAGE, FILE_SELECT, MUTE, PLAYBACK, FILE_REQUEST, SET_NAME
} command;

#endif
